export const PRESETS: Record<string, string> = {
    "E-Commerce": JSON.stringify([
        { id: 1, name: "Neural Interface", price: 2999, stock: 45, category: "Hardware", active: true },
        { id: 2, name: "Quantum Chip", price: 599, stock: 1200, category: "Components", active: true },
        { id: 3, name: "Holo-Display", price: 899, stock: 0, category: "Hardware", active: false },
        { id: 4, name: "Synapse Link", price: 149, stock: 500, category: "Cables", active: true },
        { id: 5, name: "Bio-Sensor", price: 299, stock: 150, category: "Sensors", active: true },
    ], null, 2),
    "Users": JSON.stringify([
        { id: "u_1", name: "Alice Chen", role: "admin", level: 5, department: "Ops", lastLogin: "2025-01-01" },
        { id: "u_2", name: "Bob Smith", role: "user", level: 2, department: "Ops", lastLogin: "2025-01-02" },
        { id: "u_3", name: "Carol Wu", role: "user", level: 2, department: "Dev", lastLogin: "2025-01-02" },
        { id: "u_4", name: "Dave Miller", role: "guest", level: 0, department: "External", lastLogin: "2024-12-30" },
    ], null, 2),
    "IoT Sensors (20 rows)": JSON.stringify(Array.from({ length: 20 }, (_, i) => ({
        deviceId: `sensor_${String(i + 1).padStart(3, '0')}`,
        type: ["temperature", "humidity", "pressure"][i % 3],
        value: Math.round((20 + Math.random() * 15) * 10) / 10,
        unit: ["°C", "%", "hPa"][i % 3],
        location: ["floor_1", "floor_2", "floor_3"][i % 3],
        timestamp: `2025-01-15T10:${String(i).padStart(2, '0')}:00Z`,
        status: "online",
    })), null, 2),
    "Server Metrics (15 rows)": JSON.stringify(Array.from({ length: 15 }, (_, i) => ({
        serverId: `srv-${["us-east", "us-west", "eu-central"][i % 3]}-${(i % 5) + 1}`,
        region: ["us-east", "us-west", "eu-central"][i % 3],
        cpuUsage: Math.round(Math.random() * 100),
        memoryUsage: Math.round(Math.random() * 100),
        diskUsage: Math.round(Math.random() * 100),
        activeConnections: Math.floor(Math.random() * 500),
        status: i % 10 === 0 ? "warning" : "healthy",
        lastPing: Date.now() - Math.floor(Math.random() * 60000),
    })), null, 2),
    "Events Log (25 rows)": JSON.stringify(Array.from({ length: 25 }, (_, i) => ({
        eventId: i + 1,
        type: ["click", "view", "purchase", "signup"][i % 4],
        userId: `user_${Math.floor(Math.random() * 100)}`,
        page: ["/home", "/products", "/cart", "/checkout"][i % 4],
        browser: ["Chrome", "Firefox", "Safari"][i % 3],
        country: ["US", "UK", "DE", "FR", "JP"][i % 5],
        timestamp: `2025-01-${String((i % 28) + 1).padStart(2, '0')}T${String(i % 24).padStart(2, '0')}:00:00Z`,
    })), null, 2),
};
