export const PRESETS: Record<string, string> = {
    "E-Commerce": JSON.stringify([
        { id: 1, name: "Neural Interface", price: 2999, stock: 45, category: "Hardware", active: true },
        { id: 2, name: "Quantum Chip", price: 599, stock: 1200, category: "Components", active: true },
        { id: 3, name: "Holo-Display", price: 899, stock: 0, category: "Hardware", active: false },
        { id: 4, name: "Synapse Link", price: 149, stock: 500, category: "Cables", active: true },
        { id: 5, name: "Bio-Sensor", price: 299, stock: 150, category: "Sensors", active: true },
    ], null, 2),
    "Users": JSON.stringify([
        { id: "u_1", name: "Alice Chen", role: "admin", level: 5, department: "Ops", lastLogin: "2025-01-01" },
        { id: "u_2", name: "Bob Smith", role: "user", level: 2, department: "Ops", lastLogin: "2025-01-02" },
        { id: "u_3", name: "Carol Wu", role: "user", level: 2, department: "Dev", lastLogin: "2025-01-02" },
        { id: "u_4", name: "Dave Miller", role: "guest", level: 0, department: "External", lastLogin: "2024-12-30" },
    ], null, 2),
    "IoT Sensors (20 rows)": JSON.stringify(Array.from({ length: 20 }, (_, i) => ({
        deviceId: `sensor_${String(i + 1).padStart(3, '0')}`,
        type: ["temperature", "humidity", "pressure"][i % 3],
        value: Math.round((20 + Math.random() * 15) * 10) / 10,
        unit: ["°C", "%", "hPa"][i % 3],
        location: ["floor_1", "floor_2", "floor_3"][i % 3],
        timestamp: `2025-01-15T10:${String(i).padStart(2, '0')}:00Z`,
        status: "online",
    })), null, 2),
    "Server Metrics (15 rows)": JSON.stringify(Array.from({ length: 15 }, (_, i) => ({
        serverId: `srv-${["us-east", "us-west", "eu-central"][i % 3]}-${(i % 5) + 1}`,
        region: ["us-east", "us-west", "eu-central"][i % 3],
        cpuUsage: Math.round(Math.random() * 100),
        memoryUsage: Math.round(Math.random() * 100),
        diskUsage: Math.round(Math.random() * 100),
        activeConnections: Math.floor(Math.random() * 500),
        status: i % 10 === 0 ? "warning" : "healthy",
        lastPing: Date.now() - Math.floor(Math.random() * 60000),
    })), null, 2),
    "Events Log (25 rows)": JSON.stringify(Array.from({ length: 25 }, (_, i) => ({
        eventId: i + 1,
        type: ["click", "view", "purchase", "signup"][i % 4],
        userId: `user_${Math.floor(Math.random() * 100)}`,
        page: ["/home", "/products", "/cart", "/checkout"][i % 4],
        browser: ["Chrome", "Firefox", "Safari"][i % 3],
        country: ["US", "UK", "DE", "FR", "JP"][i % 5],
        timestamp: `2025-01-${String((i % 28) + 1).padStart(2, '0')}T${String(i % 24).padStart(2, '0')}:00:00Z`,
    })), null, 2),
    "API Response (50 rows)": JSON.stringify(Array.from({ length: 50 }, (_, i) => ({
        id: `req_${String(i + 1).padStart(4, '0')}`,
        endpoint: ["/api/users", "/api/products", "/api/orders", "/api/inventory", "/api/analytics"][i % 5],
        method: ["GET", "POST", "PUT", "DELETE"][i % 4],
        statusCode: [200, 201, 400, 401, 404, 500][i % 6],
        responseTimeMs: Math.floor(Math.random() * 500) + 10,
        userId: i % 3 === 0 ? null : `user_${Math.floor(Math.random() * 1000)}`,
        cached: i % 4 === 0,
        region: ["us-east-1", "us-west-2", "eu-west-1", "ap-southeast-1"][i % 4],
        timestamp: `2025-01-15T${String(Math.floor(i / 2)).padStart(2, '0')}:${String((i * 3) % 60).padStart(2, '0')}:00Z`,
    })), null, 2),
    "Chat Messages (40 rows)": JSON.stringify(Array.from({ length: 40 }, (_, i) => ({
        messageId: i + 1,
        conversationId: `conv_${Math.floor(i / 5) + 1}`,
        role: i % 2 === 0 ? "user" : "assistant",
        content: [
            "How do I reset my password?",
            "You can reset your password by clicking the 'Forgot Password' link on the login page.",
            "What are your business hours?",
            "We are open Monday through Friday, 9 AM to 5 PM EST.",
            "Can I track my order?",
            "Yes, you can track your order using the tracking number sent to your email.",
            "Do you offer refunds?",
            "We offer full refunds within 30 days of purchase.",
            "How do I contact support?",
            "You can reach our support team at support@example.com.",
        ][i % 10],
        timestamp: `2025-01-15T${String(10 + Math.floor(i / 4)).padStart(2, '0')}:${String((i * 2) % 60).padStart(2, '0')}:00Z`,
        tokenCount: Math.floor(Math.random() * 100) + 5,
    })), null, 2),
    "Financial Transactions (100 rows)": JSON.stringify(Array.from({ length: 100 }, (_, i) => ({
        txId: `TX${String(i + 1).padStart(6, '0')}`,
        type: ["deposit", "withdrawal", "transfer", "payment"][i % 4],
        amount: Math.round((Math.random() * 10000 + 10) * 100) / 100,
        currency: ["USD", "EUR", "GBP"][i % 3],
        fromAccount: `ACC${String(Math.floor(Math.random() * 1000)).padStart(4, '0')}`,
        toAccount: i % 4 === 3 ? null : `ACC${String(Math.floor(Math.random() * 1000)).padStart(4, '0')}`,
        status: ["completed", "pending", "failed"][i % 20 === 0 ? 2 : i % 10 === 0 ? 1 : 0],
        fee: Math.round(Math.random() * 10 * 100) / 100,
        timestamp: `2025-01-${String((i % 28) + 1).padStart(2, '0')}T${String(i % 24).padStart(2, '0')}:${String((i * 7) % 60).padStart(2, '0')}:00Z`,
    })), null, 2),
    "RAG Documents (30 rows)": JSON.stringify(Array.from({ length: 30 }, (_, i) => ({
        docId: `doc_${String(i + 1).padStart(3, '0')}`,
        title: [
            "Introduction to Machine Learning",
            "Data Preprocessing Techniques",
            "Neural Network Architectures",
            "Natural Language Processing Basics",
            "Computer Vision Fundamentals",
            "Reinforcement Learning Overview",
        ][i % 6],
        source: ["arxiv.org", "wikipedia.org", "documentation", "textbook", "blog"][i % 5],
        chunkIndex: (i % 5) + 1,
        totalChunks: 5,
        tokenCount: Math.floor(Math.random() * 400) + 100,
        embedding: Array.from({ length: 8 }, () => Math.round(Math.random() * 1000) / 1000),
        relevanceScore: Math.round(Math.random() * 100) / 100,
        metadata: { author: ["Smith", "Johnson", "Williams", "Brown"][i % 4], year: 2020 + (i % 5) },
    })), null, 2),
};
